Bug fixes
KingdomFirst/Bulldozer pull request #105
Opened 2024-07-05 19:48 UTC by guymaness2

### Description 

##### What does the change add or fix?

* Fixed issue with nuget package/ Rock reference dlls related to CacheManager.Core.
* Fixed bug causing some GroupMember roles to not import properly during group member import.
* Fixed bug causing some GroupType roles to duplicate on import.

---------

### Release Notes 

##### What does the change add or fix in a succinct statement that will be read by clients?

* Fixed issue with nuget package/ Rock reference dlls related to CacheManager.Core.
* Fixed bug causing some GroupMember roles to not import properly during group member import.
* Fixed bug causing some GroupType roles to duplicate on import.

---------

### Requested By

##### Who reported, requested, or paid for the change?

Warranty

---------

### Screenshots

##### Does this update or add options to the block UI?

no

---------

### Change Log

##### What files does it affect?

* Bulldozer.BinaryFile/app.config
* Bulldozer.CSV/Maps/Group.cs
* Bulldozer.CSV/app.config
* Bulldozer.Example/App.config
* Bulldozer.FellowshipOne/app.config
* Bulldozer/App.config
* Bulldozer/packages.config
* packages/Rock/CacheManager.Core.dll
* packages/Rock/CacheManager.SystemRuntimeCaching.dll

---------

### Migrations/External Impacts

##### Is it a breaking change for other versions/clients?

no

2024-07-08 16:51 UTC, nateh777 commented on Bulldozer.CSV/Maps/Group.cs
> +                            Name = roleName,
@guymaness2 because of this change can you please remove Line 1258? It should no longer be used anywhere?

2024-07-08 16:52 UTC, nateh777 requested changes
See comment about line needing to be removed, https://github.com/KingdomFirst/Bulldozer/pull/105/files#r1668972064

2024-07-16 18:22 UTC, guymaness2 commented
@nateh777 all conversations resolved

2024-07-25 16:43 UTC, nateh777 approved these changes

2024-07-25 16:44 UTC, merged