Fix email regex
KingdomFirst/Bulldozer pull request #37
Opened 2020-10-31 15:47 UTC by lauweijie

Fixes #36.

Regex source: https://stackoverflow.com/a/16168103

### Release Notes 

##### What does the change add or fix in a succinct statement that will be read by clients?

- Fix email validation regex

2020-11-12 14:39 UTC, lauweijie commented
Any updates to this?

2020-12-04 00:32 UTC, nateh777 requested changes
This is an untested change as it would fail using `emailString` instead of `email` the proper variable. I would prefer not to change the email Regex so drastically, though it might be cited as valid according to stack overflow it would require some testing. Which will require a test on a migration by us at a later time. If you would like a change to be made quicker I have added a suggested change to the regex that should accommodate the situation explained in the issue. If you can accept the suggestion and test it we can get this merged.

2020-12-04 00:32 UTC, nateh777 commented on Bulldozer/Utility/Extensions.cs
> +            return Regex.IsMatch( emailString, @"\A(?:[a-z0-9!#$%&'*+/=?^_`{|}~-]+(?:\.[a-z0-9!#$%&'*+/=?^_`{|}~-]+)*@(?:[a-z0-9](?:[a-z0-9-]*[a-z0-9])?\.)+[a-z0-9](?:[a-z0-9-]*[a-z0-9])?)\Z", RegexO
```suggestion
            return Regex.IsMatch( email, @"^(?!((http|https):\/\/|www\.))[\w\.\'_%-]+(\+[\w-]*)?@([\w-]+\.)+[\w-]+$" );
```

2020-12-14 16:06 UTC, nateh777 approved these changes

2020-12-14 16:07 UTC, merged